### ISSUE TITLE
error while running dotplot analysis

### ISSUE THREAD

**Issue by amit4mchiba** [SunPengChuan/wgdi-example#2]
Hi Pengchuan Sun,

My name is Amit, and I am very fascinated with your tool. I, therefore, wanted to do a test run, and here is what I did.

Firstly, I installed wgdi using conda. Then, I downloaded the wgdi-example from GitHub. Next, I obtained vvi161s.pep.fa, vvi161s.cdc.fa, vvi161s.gff, and vvi161s.lens file. Next, I performed a blast search using the following command-
python ./wgdi-example/Karyotype_Evolution_Example/blast/rundiamond.py vvi161s.pep.fa vvi161s.pep.fa vvi161s vvi_vvi.blast

Afterwards, I got total.conf file as mentioned in the WGDI documentation website, which is like this-
[dotplot]
blast = vvi_vvi.blast
gff1 =  vvi161s.gff
gff2 =  vvi161s.gff
lens1 = vvi161s.lens
lens2 = vvi161s.lens
genome1_name =  Vitis venifera
genome2_name =  Vitis venifera
multiple  = 1
score = 100
evalue = 1e-5
repeat_number = 10
position = order
blast_reverse = false
ancestor_left = none
ancestor_top = none
markersize = 0.5
figsize = 10,10
savefig = savefile(.png, .pdf, .svg)

Following this, I run command- wgdi -d total.conf
And I am getting this error-
(wgdi) ./Vitis_vinifera$ wgdi -d total.conf
blast  =  vvi_vvi.blast
gff1  =  vvi161s.gff
gff2  =  vvi161s.gff
lens1  =  vvi161s.lens
lens2  =  vvi161s.lens
genome1_name  =  Vitis venifera
genome2_name  =  Vitis venifera
multiple  =  1
score  =  100
evalue  =  1e-5
repeat_number  =  10
position  =  order
blast_reverse  =  false
ancestor_left  =  none
ancestor_top  =  none
markersize  =  0.5
figsize  =  10,10
savefig  =  savefile(.png, .pdf, .svg)
/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/base.py:213: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for name, group in gff.groupby(['chr']):
/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/base.py:213: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for name, group in gff.groupby(['chr']):
/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/dotplot.py:37: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  index = [group.sort_values(by=[11], ascending=[False])[:repeat_number].index.tolist()
Traceback (most recent call last):
  File "/mnt/HD1/miniconda3/envs/wgdi/bin/wgdi", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 163, in main
    module_to_run(arg, value)
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 122, in module_to_run
    run_subprogram(program, conf, name)
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 87, in run_subprogram
    r.run()
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/dotplot.py", line 118, in run
    plt.savefig(self.savefig, dpi=300)
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/pyplot.py", line 954, in savefig
    res = fig.savefig(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/figure.py", line 3274, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2285, in print_figure
    with cbook._setattr_cm(self, manager=None), \
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/mnt/HD1/miniconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2192, in _switch_canvas_and_return_print_method
    raise ValueError(
ValueError: Format 'svg)' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff, webp)

I am unsure where I am wrong or if I need to install any package or something. I will be grateful if you could help me out.

Thank you so much,

with best regards
Amit

**Comment by amit4mchiba** [comment]
Thank you so much for your help. I could run the program by using savefig = vvi_vvi.pdf
It worked for me. Thank you so much again.
